blank_issues_enabled: false
contact_links:
  - name: Ryujinx Troubleshooting/Support 
    url: https://discord.gg/N2FmfVc
    about: For support and technical issues, please come to our Discord server.
