blank_issues_enabled: false
contact_links:
  - name: Ryujinx Discord
    url: https://discord.gg/N2FmfVc
    about: This is for game compatibility list. For support and technical issues, please come to our Discord server.
